Improve documentation for generating PEP pages.
python/pythondotorg pull request #1015
Opened 2016-09-21 04:54 UTC by Mariatta

Add instruction on how to clone PEP repo.
Also be more specific of where pep2html.py and genpepindex.py should be run from.

2016-09-21 10:44 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +      $ hg clone https://hg.python.org/peps/
https://github.com/python/peps.git

2016-09-21 10:45 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +
remove empty line

2016-09-21 10:47 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +      $ pep2html.py
`./pep2html.py` or `python pep2html.py` would be less cryptic.

2016-09-21 10:48 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +      $ pep2html.py
Alternatively, we can just add `make -j` here.

2016-09-21 10:51 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +2. From cloned PEP Repository, run::
From *the* cloned [...]

2016-09-21 10:51 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +1. Check out PEP Repository, if you have not done so::
Clone the PEP Repository, [...]

2016-09-21 10:53 UTC, berkerpeksag commented on docs/source/pep_generation.rst
> +4. After all PEP pages are generated into HTML, run in pythondotorg repository::
[...] run in your \`\`pythondotorg\`\` clone::

2016-09-21 10:55 UTC, berkerpeksag requested changes
Could you also update the repo URL in line 57:

```
.. _PEP Repository: https://hg.python.org/peps/
```

2016-09-22 03:51 UTC, Mariatta commented
Thanks, @berkerpeksag I made the changes as suggested.

2016-09-22 10:21 UTC, berkerpeksag approved these changes

2016-09-22 10:21 UTC, merged

2016-09-22 10:21 UTC, berkerpeksag commented
Thanks!