Add support for syntax highlighting in PEPs
python/pythondotorg pull request #1063
Opened 2017-03-16 14:57 UTC by ilevkivskyi

Fixes #889 

This PR provides two options for syntax highlighting in PEPs:
* Automatic highlighting of all literal blocks using Python syntax for PEPs in ``PURE_PYTHON_PEPS``. I added few examples there just to illustrate the idea.
* Now there is support for reST ``.. code:: your_favourite_language``. Such literal blocks will be highlighted using the corresponding syntax.

This PR requires [Pygments](https://pypi.python.org/pypi/Pygments) 2.1.3.

I added a CSS based on Pygments default (I made very few modifications, to match the "general spirit" of the site).

2017-03-23 00:44 UTC, Mariatta commented
Thanks @ilevkivskyi , this seems to work well :)
I tested this locally, using the change made in https://github.com/python/peps/pull/229

Here's how the colors look like
<img width="629" alt="screen shot 2017-03-22 at 5 37 48 pm" src="https://cloud.githubusercontent.com/assets/5844587/24226933/cab06a92-0f26-11e7-9068-60317b548082.png">

2017-03-23 21:08 UTC, berkerpeksag requested changes
Thanks for the PR! How hard would be to add some tests?

2017-03-23 21:08 UTC, berkerpeksag commented on templates/pages/pep-page.html
> +<link rel="stylesheet" type="text/css" href="/static/stylesheets/pygments_default.css" />
We should use `{{ STATIC_URL }}` instead of hardcoding `/static/`.

2017-03-23 21:08 UTC, berkerpeksag commented on requirements.txt
> +pygments==2.1.3
Could you add a comment so we won't forget to remove the dependency when we move PEPs to RtD?

2017-03-23 21:08 UTC, berkerpeksag commented on peps/converters.py
> +    # Fix hihglighting code
Typo: hihglighting

2017-03-23 21:08 UTC, berkerpeksag commented on peps/converters.py
> +PURE_PYTHON_PEPS = [483, 484, 526]
This is probably not important to have a constant. I'd say either inline it or add a comment to explain why we need it.

2017-03-23 21:08 UTC, berkerpeksag commented on peps/converters.py
> +    code_blocks = pep_content.find_all("pre", class_="code")
Nitpick: I know we are already pretty inconsistent with this, but please use single quotes where possible.

2017-03-23 23:43 UTC, ilevkivskyi commented
@berkerpeksag Thank you for review! I addressed your comments (including a simple test) in a new commit.

2017-04-26 10:59 UTC, ilevkivskyi commented
This is still marked as "Changes requested", although I think I had implemented the required changes a month ago. Should anything more be changed here?

2017-04-26 11:27 UTC, berkerpeksag commented
Yeah, that's because I haven't had a chance to look at the new version of the PR yet.

2017-06-03 12:44 UTC, berkerpeksag commented
Thanks for the PR again, @ilevkivskyi. Your changes look good to me, but unfortunately I have to reject this PR. Our ultimate goal is to move PEPs from python.org to Read the Docs so my preference is only fixing bugs in python.org infrastructure and save feature requests to the new infrastructure (also, note that we are going to get this feature for free when we move to RtD)

2017-06-03 12:44 UTC, closed without merging

2017-12-04 18:53 UTC, brettcannon commented
Maybe we should open this again since getting the PEPs over to Read the Docs is moving at the speed of mud?

2017-12-04 23:12 UTC, ilevkivskyi commented
> Maybe we should open this again since getting the PEPs over to Read the Docs is moving at the speed of mud?

I am fine with both possibilities: if it stays closed -- less works for me, if it is reopened -- we will have syntax highlighting sooner :-)

2020-09-21 20:59 UTC, hugovk commented
> Maybe we should open this again since getting the PEPs over to Read the Docs is moving at the speed of mud?

Three years on: I agree, it'd be great get colouring in whilst waiting on RtD (this big recent effort has stalled: https://github.com/python/peps/pull/1385). I find highlighted code much easier to read.

I've rebased and re-opened this as PR https://github.com/python/pythondotorg/pull/1638.