Topic/sponsorship form fixes
python/pythondotorg pull request #1761
Opened 2021-04-21 14:53 UTC by berinhard

Fixes #1760 

Here's a screen shot of both sticky header and custom fee message:

![Screenshot from 2021-04-21 11-49-32](https://user-images.githubusercontent.com/238223/115574192-cd1e2b80-a297-11eb-9c4a-73153f38d4a0.png)

@ewdurbin I felt that adding a message was less disruptive with package header row organization than replacing the fee by a custom message. Even though, you can see that when the message appears, the header changes its heights and it annoys me a little bit. I didn't worry that much with the texting part as well, so review is needed.

2021-04-22 14:24 UTC, ewdurbin requested changes
In review, two small copy changes and a new request are made.

Additionally, as an aside, is it possible we could hide the radio buttons in the `package-input` elements?

2021-04-22 14:24 UTC, ewdurbin commented on templates/sponsors/sponsorship_benefits_form.html
> +      <p><small>Obs: the listed fees are only valid if no changes were made to Sponsorship Package's default benefits.</small></p>
Not sure what "Obs" means.

Copy can read "The listed sponsorship costs are subject to change if customization to selected benefits are made."

2021-04-22 14:24 UTC, ewdurbin commented on templates/sponsors/sponsorship_benefits_form.html
> +               <span class="package-price">${{ package.sponsorship_amount|intcomma }}</span>
I wonder if we could add a hidden `*` that is also unhidden with the custom-fee message.

Copy for that message would then become `* Subject to change based on customization`

2021-04-23 15:53 UTC, berinhard commented on templates/sponsors/sponsorship_benefits_form.html
> +      <p><small>Obs: the listed fees are only valid if no changes were made to Sponsorship Package's default benefits.</small></p>
Ops, "Obs" is a common portuguese thing that I thought it did exist in english as well. It's like an abreviation for observations, amendments, disclaimers, etc.

2021-04-27 13:36 UTC, berinhard commented
@ewdurbin this PR is ready for a final review :+1:

2021-05-03 19:42 UTC, ewdurbin approved these changes

2021-05-03 19:42 UTC, merged