fix input-output order in interpreter example
python/pythondotorg pull request #1763
Opened 2021-04-27 07:15 UTC by sblondon

The output of `input()` function should be printed immediately, not merged with the output of `print()` function:

```
>>> name = input('What is your name?\n')
What is your name?\nPython
>>> print('Hi, %s.' % name)
Hi, Python.
>>>
```

2021-04-27 13:13 UTC, berinhard approved these changes
Thanks for the catch.

2021-05-09 14:38 UTC, sblondon commented
Thanks @berinhard  for the review. Do we need to ping someone else for the merge?

2021-05-10 13:58 UTC, berinhard commented
Maybe a quick review from @ewdurbin or @Mariatta would be nice. Although I've been working on this code base for the last months, I'm not comfortable on merging PRs as the only reviewer.

2021-05-10 14:07 UTC, ewdurbin requested changes

2021-05-10 14:07 UTC, ewdurbin commented on codesamples/factories.py
> +            >>> print('Hi, %s.' % name)
I think we should highlight f-strings while we're here!

```suggestion
            >>> print(f'Hi, {name}.')
```

2021-05-10 14:08 UTC, ewdurbin commented on codesamples/factories.py
> +            >>> print('Hi, %s.' % name)
If there's no objection to this, I'm happy to commit the suggestion and merge the PR. Thank you @sblondon

2021-05-10 20:19 UTC, sblondon commented on codesamples/factories.py
> +            >>> print('Hi, %s.' % name)
It's good for me.

There is a PR converting the string to f-string created by wkeithvan before this PR : https://github.com/python/pythondotorg/pull/1539 I guess we need to do something to it (like closing it with a link to this PR).

2021-05-10 20:22 UTC, sblondon commented on codesamples/factories.py
> +            >>> print('Hi, %s.' % name)
I committed your suggestion and added wkeithvan and ewdurbin in the commit details.

2021-05-11 20:51 UTC, ewdurbin approved these changes

2021-05-11 20:51 UTC, ewdurbin commented
Thank you @sblondon

2021-05-11 20:51 UTC, merged

2022-11-04 15:31 UTC, sblondon commented
The fixed version is not visible on python.org. I hoped the release of python3.11 would embed it automatically but I was wrong.

Who should I request to push it publicly?

2022-11-04 15:39 UTC, ewdurbin commented
Didn't see the very bottom of the file where these load data into a model, thought they were generated from the factory code. Update has been applied.