Add a test to ensure not have missing migrations
python/pythondotorg pull request #1839
Opened 2021-08-10 18:51 UTC by luzfcb

2021-08-11 15:41 UTC, berinhard requested changes
@luzfcb I think failing tests because migrations are missing can be something annoying under certain scenarios (configuring blank for admin forms, for example), even though having this check is definitely a nice to have. What do you think about, instead of having these tests, adding a call for `python manage.py makemigrations --dry-run --check` to our CI file? 

In my opinion this sounds better because the contributor will still have a warning about the missing migration without having a direct affect on their development workflow.

2021-08-19 12:57 UTC, berinhard approved these changes

2021-08-24 15:37 UTC, luzfcb commented
@berinhard I updated pr to use Github Actions instead of Travis-ci

2021-08-24 19:22 UTC, berinhard approved these changes

2022-03-15 12:30 UTC, raghavthind2005 approved these changes

2024-06-21 00:00 UTC, ewdurbin commented
Closed by https://github.com/python/pythondotorg/pull/2248

2024-06-21 00:00 UTC, closed without merging